export const NEETO_PRODUCTS = [
  "neetocal",
  "neetoform",
  "neetorecord",
  "neetoinvoice",
  "neetodesk",
  "neetochat",
  "neetokb",
  "neetosite",
  "neetorunner",
  "neetowireframe",
  "neetoengage",
  "neetoquiz",
  "neetoreplay",
  "neetoplanner",
  "neetocrm",
  "neetopublish",
  "neetocourse",
  "neetotestify",
  "neetocode",
  "neetogit",
  "neetoci",
  "neetodeploy",
  "neetoplaydash",
  "neetotower",
];

export const TLD: Record<string, string> = {
  staging: "neetoauth.net",
  development: ".lvh.me:9000",
  production: "neetoauth.com",
};
